version: '3'
services:

  backend:
    container_name: car-rest-service-backend
    hostname: backend
    depends_on:
      - keycloak
      - database-postgres
    environment:
      CAR_REST_SERVICE_DB_USER_PASSWORD: ${CAR_REST_SERVICE_DB_USER_PASSWORD}
      CAR_REST_SERVICE_KEYCLOAK_CLIENT_SECRET: ${CAR_REST_SERVICE_KEYCLOAK_CLIENT_SECRET}
      spring.datasource.url: jdbc:postgresql://db:5432/car-db
    build: ./
    ports:
      - "8080:8080"
    networks:
      - keycloak-net

  keycloak:
    container_name: car-rest-service-keycloak
    hostname: keycloak
    image: quay.io/keycloak/keycloak:24.0.5
    ports:
      - "9080:9080"
    networks:
      - keycloak-net
    volumes:
      - ./keycloak/config:/opt/keycloak/data/import
    environment:
      CAR_REST_SERVICE_KEYCLOAK_CLIENT_SECRET: ${CAR_REST_SERVICE_KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 9080
    entrypoint: [ "/opt/keycloak/bin/kc.sh", "start-dev", "--import-realm" ]

  database-postgres:
    container_name: car-rest-service-db
    hostname: db
    image: "postgres:16"
    ports:
      - "5434:5432"
    networks:
      - keycloak-net
    environment:
      POSTGRES_DB: car-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  keycloak-net: {}
